name: Daily Changes

on:
  schedule:
    - cron: '20 7 * * *' # Runs daily at 20 minutes past 7 AM UTC
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # Install dependencies
      - name: Install dependencies
        run: npm install
      # Run the change job with Supabase credentials from secrets
      - name: Run change job
        run: node change-job.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SCALEWAY_API_KEY: ${{ secrets.SCALEWAY_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          LITERAL_API_KEY: ${{ secrets.LITERAL_API_KEY }}