name: Daily Changes

on:
  schedule:
    - cron: '20 0 * * *' # Runs daily at 20 minutes past midnight UTC
    workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run change job
        run: node change-job.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}